on:
  push:
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: unit
jobs:
  test:
    # Pin to `20.04` instead of `ubuntu-latest`, until ubuntu-latest migration is complete
    # See also <https://github.com/foundry-rs/foundry/issues/3827>
    name: test (partition ${{ matrix.partition }}/${{ strategy.job-total }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        partition: [1, 2, 3]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Sccache Setup
        # Just for test, come back to upstream after released
        uses: Xuanwo/sccache-action@c94e27bef21ab3fb4a5152c8a878c53262b4abb0
        with:
          version: "v0.4.0-pre.6"

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run tests
        run: |
          cargo llvm-cov nextest --lcov --output-path lcov.info \
            --locked --workspace --all-features \
            --partition hash:${{ matrix.partition }}/${{ strategy.job-total }} \
            -E 'kind(lib)' -E 'kind(bin)' -E 'kind(proc-macro)'
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unit-tests

  eth-blockchain:
    name: ethereum / state tests (stable)
    runs-on: ubuntu-latest
    env:
      RUST_LOG: info,sync=error
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Checkout ethereum/tests
        uses: actions/checkout@v2
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run Ethereum tests
        run: cargo run --release -- test-chain ethtests/BlockchainTests/GeneralStateTests/

  doc-test:
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run doctests
        run: cargo test --doc --all --all-features
